# Dependabot config
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain Nuget dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
